# -*- coding: utf-8 -*-
"""Jual_Rumah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBCAZstLzLwKltJYHAOifP7OusCmeCxC
"""

!pip install streamlit pillow

import streamlit as st
from PIL import Image
import requests
from io import BytesIO
import os

# Konfigurasi halaman
st.set_page_config(
    page_title="DiJual",
    page_icon="🏠",
    layout="centered"
)

# CSS untuk styling
st.markdown("""
<style>
    .main-header {
        text-align: center;
        color: #2E86AB;
        margin-bottom: 30px;
    }
    .property-card {
        border: 2px solid #2E86AB;
        border-radius: 15px;
        padding: 25px;
        margin: 20px 0;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
        background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
    }
    .price-tag {
        background: linear-gradient(135deg, #FF6B6B 0%, #FF8E53 100%);
        color: white;
        padding: 12px 25px;
        border-radius: 25px;
        font-weight: bold;
        font-size: 1.5em;
        text-align: center;
        display: inline-block;
        margin: 10px 0;
    }
    .feature-box {
        background-color: white;
        border-radius: 10px;
        padding: 15px;
        margin: 10px 0;
        border-left: 4px solid #2E86AB;
    }
    .whatsapp-button {
        background: linear-gradient(135deg, #25D366 0%, #128C7E 100%);
        color: white;
        padding: 15px 30px;
        border-radius: 10px;
        text-decoration: none;
        display: block;
        text-align: center;
        font-weight: bold;
        font-size: 1.2em;
        margin: 20px 0;
        transition: all 0.3s ease;
    }
    .image-gallery {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
        margin: 20px 0;
    }
</style>
""", unsafe_allow_html=True)

# Data properti tunggal dengan link Google Drive
property_data = {
    "title": "Rumah Nyaman Siap Huni Di Lingkungan Aman Dan Bebas Banjir",
    "price": "Rp 2.950.000.000",
    "type": "Rumah",
    "bedrooms": 5,
    "bathrooms": 4,
    "area": "172 m²",
    "land_size": "128 m²",
    "location": "Villa Bogor Indah",
    "year_built": 2020,
    "certificate": "SHM",
    "description": """Bayangkan pulang setiap hari ke rumah yang tenang, nyaman, dan strategis ✨.Rumah ini bukan sekadar tempat tinggal, tapi investasi masa depan keluarga Anda.

Fasilitas:
• Fully furnished
• Lokasi hanya 10 menit ke sekolah & pusat belanja
• Kamar mandi utama dengan bathtub dan water heater gas
• Dapur modern rapi dengan meja bar
• Carport untuk 2 mobil + motor
• Taman pribadi yang asri
• Keamanan 24 jam
• Kolam renang pribadi
""",
    "whatsapp_number": "62816100334",
    "contact_name": "Hery",
    # Ganti dengan link Google Drive Anda
    "drive_images": [
        "https://drive.google.com/file/d/1Tfwc1rcCdu6U5mQcgyiCFCAhw1IYe9Lv/view?usp=share_link",  # Foto All
        "https://drive.google.com/file/d/11IDFfruSx6F8-tZRgptWdnIlbRjn3tO1/view?usp=share_link",  # Foto depan
        "https://drive.google.com/file/d/1RhtfS6pW5HPw1ituzugA8w3nIyPvJKdn/view?usp=share_link",  # Living room
        "https://drive.google.com/file/d/1J0pP9aoWojfHgfGR7_xff7Uh-xyBjBJ9/view?usp=share_link",  # Ruang makan
        "https://drive.google.com/file/d/1mZ2rR2RFEVaT7mFTkv4DY40f4jVW0wk9/view?usp=share_link",  # Kamar tidur 1
        "https://drive.google.com/file/d/1mZ2rR2RFEVaT7mFTkv4DY40f4jVW0wk9/view?usp=share_link",  # Kamar tidur 2
        "https://drive.google.com/file/d/1QPdrGj5acppst_B5ssjECn_vHs6oGtaP/view?usp=share_link",  # Kamar mandi
    ]
}

# Fungsi untuk load image dari Google Drive
def load_image_from_drive(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        image = Image.open(BytesIO(response.content))
        return image
    except Exception as e:
        st.error(f"Error loading image from {url}: {e}")
        return None

# Header utama
st.markdown('<div class="main-header">', unsafe_allow_html=True)
st.title("🏠 PROPERI EKSKLUSIF")
st.markdown("### Rumah Impian Anda Menanti")
st.markdown("</div>", unsafe_allow_html=True)

# Bagian gambar properti
st.markdown("## 📷 Galeri Properti")

if property_data["drive_images"]:
    # Tampilkan gambar utama (gambar pertama)
    main_image = load_image_from_drive(property_data["drive_images"][0])
    if main_image:
        st.image(main_image, use_column_width=True, caption="Tampilan Depan Properti")

    # Tampilkan gambar tambahan
    if len(property_data["drive_images"]) > 1:
        st.subheader("📸 Foto Lainnya")

        # Tampilkan dalam columns
        cols = st.columns(2)
        for i, image_url in enumerate(property_data["drive_images"][1:]):
            image = load_image_from_drive(image_url)
            if image:
                with cols[i % 2]:
                    st.image(image, use_column_width=True, caption=f"Foto {i+2}")
else:
    st.warning("Tidak ada gambar yang tersedia.")

# Informasi properti
st.markdown("## ℹ️ Informasi Detail Properti")
st.markdown('<div class="property-card">', unsafe_allow_html=True)

st.markdown(f"<div class='price-tag'>{property_data['price']}</div>", unsafe_allow_html=True)
st.markdown(f"### {property_data['title']}")

# Spesifikasi properti
col1, col2 = st.columns(2)

with col1:
    st.markdown('<div class="feature-box">', unsafe_allow_html=True)
    st.markdown(f"**🏠 Tipe Properti:** {property_data['type']}")
    st.markdown(f"**📍 Lokasi:** {property_data['location']}")
    st.markdown(f"**📏 Luas Bangunan:** {property_data['area']}")
    st.markdown(f"**📐 Luas Tanah:** {property_data['land_size']}")
    st.markdown("</div>", unsafe_allow_html=True)

with col2:
    st.markdown('<div class="feature-box">', unsafe_allow_html=True)
    st.markdown(f"**🛏️ Kamar Tidur:** {property_data['bedrooms']}")
    st.markdown(f"**🚿 Kamar Mandi:** {property_data['bathrooms']}")
    st.markdown(f"**📅 Tahun Dibangun:** {property_data['year_built']}")
    st.markdown(f"**📜 Sertifikat:** {property_data['certificate']}")
    st.markdown("</div>", unsafe_allow_html=True)

# Deskripsi
st.markdown("### 📝 Deskripsi Properti")
st.markdown(f"<div class='feature-box'>{property_data['description']}</div>", unsafe_allow_html=True)

st.markdown("</div>", unsafe_allow_html=True)

# Tombol WhatsApp
st.markdown("## 📞 Hubungi Kami")
st.markdown('<div class="feature-box">', unsafe_allow_html=True)

whatsapp_message = f"Halo {property_data['contact_name']}, saya tertarik dengan properti {property_data['title']} yang Anda tawarkan. Bisa saya mendapatkan informasi lebih lanjut?"
whatsapp_link = f"https://wa.me/{property_data['whatsapp_number']}?text={whatsapp_message.replace(' ', '%20')}"

st.markdown(f"""
**Kontak Person:** {property_data['contact_name']}
**Nomor WhatsApp:** +{property_data['whatsapp_number']}
""")

if st.button("💬 Hubungi via WhatsApp", use_container_width=True):
    # Untuk Streamlit, kita perlu menggunakan JavaScript untuk membuka link baru
    js = f"window.open('{whatsapp_link}')"
    st.components.v1.html(f"<script>{js}</script>", height=0)

st.markdown("</div>", unsafe_allow_html=True)